# Environment configuration
num_envs: 4  # Number of parallel environments to run simultaneously
env_offset: [1.0, 1.0, 0.0]  # Spatial offset for parallel environments (x,y,z) to prevent overlap between environments

room:
  prim_path_prefix: "/Room_{env_id}"  # Path prefix for room prims in the stage; {env_id} is replaced with the environment index (e.g., "/Room_0")

# Object configuration
objects:
  # Path to folder containing USD files (e.g., cube.usd, cone.usd)
  # usd_folder: "/Assets/Garment"  # Path to USD files for IsaacSim's built-in geometric primitives
  num_per_env: 1  # Number of objects to load in each environment (currently 1 object per environment)
  # Common configurations shared by all objects
  common:
    # Initial position range (relative to environment offset)
    initial_pos_range: [-0.025, 0.025, 0.73, -0.025, 0.025, 0.73]
    # Initial rotation range (in degrees)
    initial_rot_range: [70, 0, -2, 73, 0, 2] 
    # Position range for soft reset (relative to environment offset)
    soft_reset_pos_range: [-0.025, 0.025, 0.73, -0.025, 0.025, 0.73] 
    # Rotation range for soft reset (in degrees)
    soft_reset_rot_range: [70, 0, -2, 73, 0, 2] 
    scale: [0.45, 0.45, 0.45]
  # Object-specific configurations (override common settings)
  # visual_material:
  #   material_usd_folder: "Assets/Material/Garment"
  particle_system:
    particle_system_enabled: True
    enable_ccd: True
    solver_position_iteration_count: 24
    max_depenetration_velocity: null
    global_self_collision_enabled: True
    non_particle_collision_enabled: True
    contact_offset: 0.005
    rest_offset: 0.0025
    particle_contact_offset: 0.005
    fluid_rest_offset: 0.0025
    solid_rest_offset: 0.0025
    wind: null
    max_neighborhood: null
    max_velocity: 5.0
  particle_material:
    adhesion: 0.0005
    adhesion_offset_scale: 0.0
    cohesion: 0.0
    particle_adhesion_scale: 0.2
    particle_friction_scale: 0.6
    drag: 0.0
    lift: 0.0
    friction: 2
    damping: 0.1
    gravity_scale: 1.5
    viscosity: null
    vorticity_confinement: null
    surface_tension: null
  garment_config:
    particle_mass: 1e-2
    self_collision: True
    self_collision_filter: True
    stretch_stiffness: 1e8
    bend_stiffness: 100.0
    shear_stiffness: 100.0
    spring_damping: 10.0
  # Texture randomization configuration
  texture_randomization:
    enable: False
    folder: "Assets/textures/surface/seen"
    min_id: 1
    max_id: 10000
    prim_path: "/World/Scene/Table038/looks/M_Table038a/UsdPreviewSurface/________7/________7"

  # Light randomization configuration
  light_randomization:
    enable: False
    prim_path: "/World/Light"
    intensity_range: [500, 3000]
    color_range: [0.0, 1.0]

