# Environment configuration
num_envs: 1  # Number of parallel environments to run simultaneously
env_offset: [1.0, 1.0, 0.0]  # Spatial offset for parallel environments (x,y,z) to prevent overlap between environments

room:
  prim_path_prefix: "/Room_{env_id}"  # Path prefix for room prims in the stage; {env_id} is replaced with the environment index (e.g., "/Room_0")

# Object configuration
objects:
  # Path to folder containing USD files (e.g., cube.usd, cone.usd)
  common:
    initial_pos_range: [-0.04, -0.05, 0.73, -0.04, -0.05, 0.73]  #[128.81421, 62.60039, 263, 128.81421, 62.60039, 263]
    initial_rot_range: [-20, -36, 0, 20, 36, 0]  #[0, 0, 0, 0, 0, 0] 
    soft_reset_pos_range: [-0.04, -0.05, 0.73, -0.04, -0.05, 0.73] 
    soft_reset_rot_range: [-20, -36, 0, 20, 36, 0]
    scale: [0.4, 0.4, 0.4]
  # Object-specific configurations (override common settings)
  # visual_material:
  #   material_usd_folder: "Assets/textures/garment"
  particle_system:
    particle_system_enabled: True
    enable_ccd: True
    solver_position_iteration_count: 32
    max_depenetration_velocity: null
    global_self_collision_enabled: True
    non_particle_collision_enabled: True
    contact_offset: 0.008
    rest_offset: 0.004
    particle_contact_offset: 0.005
    fluid_rest_offset: 0.0025
    solid_rest_offset: 0.0025
    wind: null
    max_neighborhood: null
    max_velocity: 5.0
  particle_material:
    adhesion: 0.1
    adhesion_offset_scale: 0.0
    cohesion: 0.0
    particle_adhesion_scale: 0.2
    particle_friction_scale: 0.6
    drag: 0.0
    lift: 0.0
    friction: 0.5
    damping: 0.05
    gravity_scale: 2
    viscosity: null
    vorticity_confinement: null
    surface_tension: null
  garment_config:
    particle_mass: 1e-2
    self_collision: True
    self_collision_filter: True
    stretch_stiffness: 1e8
    bend_stiffness: 5000.0
    shear_stiffness: 5000.0
    spring_damping: 10.0
  # Texture randomization configuration
  texture_randomization:
    enable: False
    folder: "Assets/textures/surface"
    min_id: 1
    max_id: 100
    prim_path: "/World/Scene/scene/Table038/looks/M_Table038a/UsdPreviewSurface/________7/________7"

  # Light randomization configuration
  light_randomization:
    enable: False
    prim_path: "/World/Light"
    intensity_range: [3500, 5000]
    color_range: [0.0, 0.2]